### ISSUE TITLE
Problem with send command from Bungee to client server

### ISSUE THREAD

**Issue by TheFonsi** [RHazDev/Sockets4MC#2]
From bungee to client is not working, but from client to bungee is working.
For latest version of sockets, dispatch and kotlin
Logs from bungee: https://pastebin.com/wBier8an
And on the lobby:  `[Sockets4MC] §aThe connection Lobby<->Bungee is available`

And on the lobby like a player when I used: /bdispatch lobby "say test" it is working, but when I used /dispatch lobby "say test" is not working.

**Comment by hazae41** [comment]
Thanks for your report

**Comment by TheFonsi** [comment]
When will be update which fixed this problem?

**Comment by hazae41** [comment]
This issue was moved to RHazDev/CommandsDispatcher#1
