### ISSUE TITLE
Current version (5.0) don't support Paper spigot

### ISSUE THREAD

**Issue by DerFrZocker** [RHazDev/Sockets4MC#3]
The current version of Sockets don't support the spigot fork Paper. The plugin itself start normal and with out any errors, but every plugin that use Sockets4MC throw always the same error: https://hastebin.com/ciqawuhequ.md

The version 4.0.8.3 works fine with paper.

**Comment by hazae41** [comment]
Okay thanks for the report,  I think I found the bug

**Comment by hazae41** [comment]
Fixed in https://github.com/RHazDev/Sockets4MC/commit/cfeb7d548f08e0c155ab97afe5d9735a0c9b71c8

**Comment by hazae41** [comment]
Update is available here: https://www.spigotmc.org/resources/sockets4mc-no-more-plugin-messaging-channels.15938/update?update=251810
